### ISSUE TITLE
Use exponential sleep for error handling.

### ISSUE THREAD

**Issue by Zylius** [ongr-io/ElasticsearchBundle#176]
Some tests in slow environments with many indexes still fail and require a quite big number of retries (like 1000) to pass. @tautrimas suggested using exponential sleep.
Also I think ElasticsearchTestCase should always check if error is of type `Service unavailable ... phase [query]` before retrying, not just any elasticsearch exception.

**Comment by tautrimas** [comment]
@saimaz, can you prioritise that?

**Comment by martiis** [comment]
The problem is that we have to delay every sent request to Elasticsearch client. I can't think of smart solution yet, but here's what i've got:
 - Create a connection/manager wrapper for testing which would delay every method.
 - Wait until events are implemented and add delayed listener before every execution in testing env.

More ideas?

**Comment by saimaz** [comment]
`sleep` usage in the manager is not an option here. IMO Much better would be to add method f.g. `delay` to the `AbstractElasticsearchTestCase` and delay connection when its needed.

**Comment by saimaz** [comment]
IMO Much better approach could be to not delete the index. Just delete the data and and force the new mapping. Index create operation is very expensive, and needs some time to relocate shards and prepare index for work. 

I'm gonna experiment and let everyone know is this helps.
