### ISSUE TITLE
Memory leak DocumentScanIterator

### ISSUE THREAD

**Issue by tfe2012** [ongr-io/ElasticsearchBundle#336]
Then you scan in offsetGet($offset) 

https://github.com/ongr-io/ElasticsearchBundle/blob/master/Result/AbstractResultsIterator.php#L89

grow $this->documents and $this->converted

**Comment by martiis** [comment]
It is growing because we need to keep track of documents and raw arrays. If f.e. you would fetch some data from the client as `RESULTS_OBJECT` then iterate some of them it would fill up the converted array, but then if you try to set a document, it is trying to keep the correct order if you would try to persist it latter. Other is that when we do scan iterations we need to know where we left off in previous scan.

If you are using scan and seeing out of memory error, dont do large iterations. try to save memory by limiting it to about 300 (depends on how much memory you are giving to php).

**Comment by tautrimas** [comment]
This issue is still valid, as discussed with @audriusb and the closed PR #350 displays a possible solution to the problem. We are using it.

**Comment by saimaz** [comment]
Solved in #405
