### ISSUE TITLE
Invalid links in documentation.

### ISSUE THREAD

**Issue by Zylius** [ongr-io/ElasticsearchBundle#352]
Relative links are invalid [here](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Resources/doc/dsl/suggesters/index.rst). Should be updated after moving.

**Comment by martiis** [comment]
But they work here http://ongr.readthedocs.org/en/latest/components/ElasticsearchBundle/dsl/suggesters/index.html

**Comment by saimaz** [comment]
There is a plan to convert docs to lovely MD format. So it will solve all issues.

**Comment by murnieza** [comment]
If page is not loaded on `readthedocs.org` refresh helps. One more reason to migrate to another documentation platform.

**Comment by saimaz** [comment]
Readthedocs sucks completely for our particular case (we are pushing multiple repos as a single). I was saying since 3 years for all the team that we should not go with Sphinx. And look whats happened :). We will definitely move to some other docs platform based on Markdown. Currently in the market there a lots of promising ones.

**Comment by saimaz** [comment]
New docs are [here](https://github.com/ongr-io/ElasticsearchBundle/blob/af88a3db57e7efebabdf446347ca68874dfb9bda/Resources/doc/index.md).
