### ISSUE TITLE
Support for inner hits

### ISSUE THREAD

**Issue by Vesquen** [ongr-io/ElasticsearchBundle#428]
It would be pretty cool to have support for inner hits:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html

**Comment by saimaz** [comment]
This is the nice feature, but it is still experimental in the elasticsearch. I'm adding it to the v1.1 milestone and if that will become stable we will definitely add a support for it.

**Comment by einorler** [comment]
At the moment it is possible to get raw inner hits from `Result::RESULTS_RAW` and `Result::RESULTS_RAW_ITERATOR`. Of course getting them isn't very user friendly that way, because one would have to go over a lot of levels of multidimensional arrays. Question is whether or not we want to introduce quite a lot of logic to the `DocumentIterator`, because the way I see it, a normal way to implement it would be to introduce logic similar to that of Aggregations.

**Comment by toooni** [comment]
@saimaz @einorler The Problem (difference to Aggregations) I see here is that inner hits should be available within a document (or at least in the same result iteration somehow).
I am just starting to understand elasticsearch and this bundle - therefore I am sorry if I misunderstood something  ;)

I've thought about a few possible solutions:
- When the nested `_source` is excluded. It may make sense to hydrate the `inner_hits` directly into the collection?
- `AbstractDocument` class which implements properties to get and set (hydration) inner hits
- `InnerHitsDocumentTrait` which implements properties (must be used explicit if inner hits can happen on a `Document`

Only the first solution would break BC. The others can just extend functionality.

**Comment by saimaz** [comment]
There are more and more inner hits support requests. Currently, I'm investigating how it can be iterated quickly as documents or something similar. 

For the quick inner hits access, there is possible to get a response from raw.

**Comment by toooni** [comment]
I made a working solution where inner_hits are embedded into the document. I do have concerns that this doesn't match the requirements of @saimaz but wanted to give the input anyway.

I do know that this only makes sense as long as the childrens are excluded from `_source` because it would be overwritten by the hits anyway.
 
https://github.com/toooni/ElasticsearchBundle/commit/4310d2b0c89b846dcbf8272504d464506f30c9e8

**Comment by saimaz** [comment]
Thanks for sharing your commit @toooni. I will borrow your commit and cherry pick to the new inner_hits iterator implementation.

**Comment by toooni** [comment]
@saimaz I hope you haven't done this yet. I had another problem which led me to change some things. https://github.com/ongr-io/ElasticsearchBundle/compare/5.0...toooni:inner_hit?expand=1

Please be aware - it is a working solution for our usecase. I haven't checked if there are cases which are different from ours which have to be considered.

**Comment by saimaz** [comment]
Thanks @toooni, looks pretty interesting.
