### ISSUE TITLE
Auto add class name prefix for fields names to avoid mapping conflicts

### ISSUE THREAD

**Issue by sidux** [ongr-io/ElasticsearchBundle#567]
If we have same field name in different document classes with different types or analysis we end up with mapping conflicts errors (2.2 elastic version), a possible solution to this is to add a prefix with class name on class fields (when we don't define any name). 
For exemple if we take a field "name" in class "product" the generated name will be "product_name" instead of "name".

**Comment by saimaz** [comment]
That's very interesting find. Is there any chance that you could provide your small document classes in a gist or just paste here. I would like to recreate the problem and think how I could solve this problem ;)

**Comment by sidux** [comment]
```
/**
 * @ES\Document
 */
class Solution extends AbstractDocument
{

    /**
     * @var string
     * @ES\Property(type="string")
     */
    protected $name;

}
```

```
/**
 * @ES\Document
 */
class Product extends AbstractDocument
{

    /**
     * @var string
     *
     * @ES\Property(type="string",  options={"analyzer":"incrementalAnalyzer"})
     */
    protected $name;
}
```

Here we have two classes where i didn't mention names so the generated mapping name in both cases will be "name". 
The problem with this is that i have different analyzers for each field and it creates mapping conflicts error in elasticsearch 2.2.
In my case i added ```@ES\Property(name="solution_name", type="string") ``` to resolve the problem but i think it will be better if it adds a prefix by itself when you don't mention any name.

**Comment by saimaz** [comment]
Well I analyzed your problem and IMO it the elasticsearch problem. This is how it works and that's it. It will be a logic fault if you will try to create on elasticsearch too. That's why we left an ability to change elasticsearch field names if the document class property name doesn't fit. To follow by your addition would add so much mess for everybody :) so we cannot change the behaviour like this. 

For quick resolve of your problem my advice would be to use multi fields here by using custom names related to analyzers or so.
