### ISSUE TITLE
Elasticsearch cannot handle float value provided as a string

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#571]
e.g. json import creates a document array where all values are strings, if in the mapping are float value, the document field won't be inserted due error. In the converter, there has to be check if value by the mapping is float or int, it has to be changed to according value type. 

https://github.com/ongr-io/ElasticsearchBundle/blob/77e264a55c97608765acf6935b86e9fdb9507d85/Result/Converter.php#L139

**Comment by mvar** [comment]
I'm reopening this, because this issue was not fully resolved.

Elasticsearch allows to set array of integers/floats to single field, but proposed logic cast array into `0`.

This line can get array which should be considered as normal behaviour:
https://github.com/ongr-io/ElasticsearchBundle/pull/585/files#diff-66c47f6e200a94aee1d79681d7459d0cR181
