### ISSUE TITLE
Why is a setter required?

### ISSUE THREAD

**Issue by robinvdvleuten** [ongr-io/ElasticsearchBundle#753]
I am currently creating a document class and as in the doctrine library, I am used to create only a getter method for the identifier so it cannot be mutated from within the application (without any brute-force). Now with this bundle, I am required to set a setter method for the identifier.
Doctrine sets the identifier upon hydration through reflection, maybe it's an idea to do this here as well. Any thoughts for this? I am definitely willing to put some effort in this with a PR 😄

**Comment by saimaz** [comment]
The setter is required for results handler to be able to create a document iterator. Metadata collector scans documents and creates instructions (it's one time operation and after it's cached) to pass it to the DocumentIterator when it needs to build document objects from the array which comes from elasticsearch.

This IMO would be a difficult task but possible to do :). I would prefer to start with #681. And make sure the metadata collector is adaptable (driver based), and in that case, document objects generation might be very reliable. 

All in all, it probably will be done in v6 because right now I'm putting all attention to Elasticsearch v5 support. The performance-wise current situation is quite good in production ENV.

**Comment by robinvdvleuten** [comment]
It's more of trying to get best practices regarding DDD in my codebase, but for now it's fine this way.
