### ISSUE TITLE
`Object` is reserved word in PHP 7.2

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchBundle#828]
Starting from PHP 7.2 we no longer can name our class `Object` which is still the case in ESB.

When trying to run project using ONGR on PHP 7.2 I get the following error: `PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in ....vendor/ongr/elasticsearch-bundle/Annotation/Object.php on line 23`

https://github.com/ongr-io/ElasticsearchBundle/blob/bf49352edfef67dde4ce4084c2a921e59a8cf7db/Annotation/Object.php#L23

Consider renaming `Object` to something not reserved.

**Comment by saimaz** [comment]
Thanks for letting know this. I am planning the nw major version (v6) to support Elasticsearch 6 and definitely will take care of this case with new changes.

**Comment by martijnhartlief** [comment]
Anyway way to quickly fix in the current version?

**Comment by saimaz** [comment]
In the current version that would be a breaking change. Can't do this.

**Comment by trickreich** [comment]
So this will fixed in version 6.*?

**Comment by saimaz** [comment]
YES ;)

**Comment by carlosdanielmou** [comment]
+1

**Comment by sdev2** [comment]
+1 Please hurry

**Comment by trevorpan** [comment]
What's the best way to move forward with this reserved word?

I'm working my way through a PHP and MySQL Web Development book by Welling and Thomson.

**Comment by kleinkoerkamp** [comment]
+1

**Comment by cadavre** [comment]
Do we have any release plan for v6?

**Comment by saimaz** [comment]
Yes. I just released (ElasticsearchDSL)[https://github.com/ongr-io/ElasticsearchDSL]. For the ElasticsearchBundle 6 version the main things I would like to change is to remove "Bundle" mappings and change them to namespaces instead to support Symfony Flex as well. And some small other fixes including support for the Elasticsearch 6 ;)

**Comment by axotion** [comment]
Any progress about this?

**Comment by TomKeur** [comment]
@saimaz Can you please give us any update? Making any progress?

**Comment by saimaz** [comment]
You can check the progress here https://github.com/ongr-io/ElasticsearchBundle/pull/840

@trandangtri is trying to help introduce SF 4 support along with PHP 7.2 here https://github.com/ongr-io/ElasticsearchBundle/issues/831

**Comment by YetiCGN** [comment]
This should be reflected in your `composer.json`. I just found out running our deploy task for the first time, because the GitLab CI Runner is already on PHP 7.2. It must be a constraint for the whole bundle, and not guarantee compatibility with ">=5.6". I thought we all learned something from the `"phpunit/phpunit": "*"` debacle. Unbounded version constraints are an anti-pattern.

**Comment by TomasVotruba** [comment]
Just dropping by... I work on a refactoring tool, that helps with PHP code migration to newer version.

I've just added PR https://github.com/rectorphp/rector/pull/657 that help with `Object` migration anywhere in the code. Class, parent, typehints, new instances etc.
It really helps with hude code base upgrades.

**Comment by ArtemSer** [comment]
Waiting for an update. Still getting an error with elastic in Sulu CMS
`  PHP Fatal error:  Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Object because 'Object' is a special class name in /home/user/sulu-demo/vendor/sulu/article-bundle/Document/LocalizationStateViewObject.php on line 14`

Is there a way to solve this problem without waiting for an update? Thanks.

**Comment by YetiCGN** [comment]
Are you using ^5.2.2? Because 5.2 is compatible with PHP 7.2

**Comment by mauricios** [comment]
I'm still having errors with PHP 7.2.12:

`The autoloader expected class "ONGR\ElasticsearchBundle\Annotation\Object" to be defined in file "/app/vendor/composer/../ongr/elasticsearch-bundle/Annotation/Object.php". The file was found but the class was not in it, the class name or namespace probably has a typo.`

**Comment by YetiCGN** [comment]
@TomasVotruba No, [Object.php](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Annotation/Object.php) needs to stay for people on PHP 7.1 and lower. Otherwise they would have to refactor all their code using the `@Object` annotation, which is a BC break. It shouldn't be used in that way, though and something else in @mauricios' code is still trying to use this annotation.

@mauricios What were you doing when this error occured? Do you use `@Object` in your code? Did you run the test suite (see #854)?

**Comment by alexander-schranz** [comment]
@YetiCGN if #860 is get merged and released we can update SuluArticleBundle to use the new Annotation.

**Comment by YetiCGN** [comment]
Great! For now we're good with our ES5-only PHP-7.2-compatible fork but it will be good for SuluArticleBundle to have this solved.

**Comment by adrienbrault** [comment]
I think this can be closed, the php 7.2 fix has been released in `v5.2.0`

**Comment by saimaz** [comment]
Indeed

**Comment by mareksuscak** [comment]
@YetiCGN We're using Sulu 1.6.24 w/ SuluArticleBundle 1.0.1 and ElasticsearchBundle 5.2.4. We recently attempted an upgrade to PHP 7.2 but we're getting the same error as mauricios. What fork are you referring to? Any pointers?

**Comment by YetiCGN** [comment]
My fork is at https://github.com/YetiCGN/SuluArticleBundle, but I just got it to run for my purposes for a project last November. No guarantees! 😉

**Comment by saimaz** [comment]
@mareksuscak can you explain a bit more about your error?

Please check you document annotations if there is used `Object` somewhere it might be a problem.

You need to change the declaration in your documents:
```
- * @ES\Object
+ * @ES\ObjectType
```

**Comment by mareksuscak** [comment]
@saimaz Thanks for the instructions. We don't use the annotation in our own code. The problem turned out to be the cache! Read [here](https://github.com/sulu/SuluArticleBundle/issues/304#issuecomment-460186439) for more.
