### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by alexander-bogomolov** [ongr-io/ElasticsearchBundle#831]
Please provide a Symfony 4 compatible version. :)

![screen-004](https://user-images.githubusercontent.com/127733/34563428-e226601e-f152-11e7-9b6b-460aee566cbf.png)

**Comment by kaanbasal** [comment]
Do you have any plan to support Symfony 4 in the near future?

**Comment by saimaz** [comment]
Yes. I have plans to add Symfony 4 and flex support to all ongr-io bundles quite soon.

**Comment by andreymeretsky** [comment]
What is estimate date of symfony 4 support?

**Comment by saimaz** [comment]
I'm working on this, but it's a huge list of changes required. Roughly I might need 1 to 3 months, thought.

**Comment by toooni** [comment]
Do you have something which you can outsource on your list? I might have some time to help you.

**Comment by saimaz** [comment]
I will create a branch today for `6.0` and some most important issues with the 'help_wanted' label.

**Comment by saimaz** [comment]
I created a PR from the local branch, where I will add some info about the new major version. Any feedback is very welcome since I can do some major and BC changes. 

https://github.com/ongr-io/ElasticsearchBundle/pull/840

**Comment by trandangtri** [comment]
Hi @saimaz 

Because Symfony released version 4 in a long time, and the needs of upgrading is very high. AFAIK, you are working on the major version of ONGR to support it and Elasticsearch 6 also. And I think it requires a huge of chances. What do you think if we break this one into 2 versions. A patch of version 5.* will support symfony 4, and version 6 will support ES6. It will solve this issue sooner than.

Just my 2 cents

**Comment by saimaz** [comment]
There is released Symfony4 support in v5.2.4, Also v6-beta is released as well.
