### ISSUE TITLE
Question: is this bundle still maintained?

### ISSUE THREAD

**Issue by wazum** [ongr-io/ElasticsearchBundle#876]
Is this bundle still maintained?
There's no action since last year and there's no action for all the other ongr.io (http://ongr.io/) bundles too (some have no updates for years).
Should we rely on this bundle or better start with the FOSElasticaBundle?

**Comment by saimaz** [comment]
It is. Take a look at the releases. There is [v6 beta](https://github.com/ongr-io/ElasticsearchBundle/releases/tag/v6.0.0-beta). This release is ready for the ES 7. Beta 2 is also about to release and the stable version after it most likely since I didn't find any major issues which can't be fixed by minor releases.
